# Generated by Django 2.2.16 on 2023-03-29 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text_comment',
            new_name='text',
        ),
    ]
